// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

<<<<<<< HEAD
import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)
=======
import AddProfileImageController from "./add_profile_image_controller"
application.register("add-profile-image", AddProfileImageController)
>>>>>>> master

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
