// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddProfileImageController from "./add_profile_image_controller"
application.register("add-profile-image", AddProfileImageController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

